# Generated by Django 5.2.13 on 2026-04-27 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_notification_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="communication_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="communication_rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="technical_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="technical_rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
