/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUploadModuleRouteImport } from './routes/_authenticated/upload-module'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedOnboardRouteImport } from './routes/_authenticated/onboard'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedModulesRouteImport } from './routes/_authenticated/modules'
import { Route as AuthenticatedManagersRouteImport } from './routes/_authenticated/managers'
import { Route as AuthenticatedInternsRouteImport } from './routes/_authenticated/interns'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated/users.$userId'
import { Route as AuthenticatedModulesModuleIdRouteImport } from './routes/_authenticated/modules/$moduleId'
import { Route as AuthenticatedModulesModuleIdTopicIdRouteImport } from './routes/_authenticated/modules/$moduleId.$topicId'
import { Route as AuthenticatedModulesModuleIdTopicIdChapterIdxRouteImport } from './routes/_authenticated/modules/$moduleId.$topicId.$chapterIdx'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadModuleRoute =
  AuthenticatedUploadModuleRouteImport.update({
    id: '/upload-module',
    path: '/upload-module',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardRoute = AuthenticatedOnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedModulesRoute = AuthenticatedModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedManagersRoute = AuthenticatedManagersRouteImport.update({
  id: '/managers',
  path: '/managers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInternsRoute = AuthenticatedInternsRouteImport.update({
  id: '/interns',
  path: '/interns',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedModulesModuleIdRoute =
  AuthenticatedModulesModuleIdRouteImport.update({
    id: '/$moduleId',
    path: '/$moduleId',
    getParentRoute: () => AuthenticatedModulesRoute,
  } as any)
const AuthenticatedModulesModuleIdTopicIdRoute =
  AuthenticatedModulesModuleIdTopicIdRouteImport.update({
    id: '/$topicId',
    path: '/$topicId',
    getParentRoute: () => AuthenticatedModulesModuleIdRoute,
  } as any)
const AuthenticatedModulesModuleIdTopicIdChapterIdxRoute =
  AuthenticatedModulesModuleIdTopicIdChapterIdxRouteImport.update({
    id: '/$chapterIdx',
    path: '/$chapterIdx',
    getParentRoute: () => AuthenticatedModulesModuleIdTopicIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interns': typeof AuthenticatedInternsRoute
  '/managers': typeof AuthenticatedManagersRoute
  '/modules': typeof AuthenticatedModulesRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboard': typeof AuthenticatedOnboardRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/upload-module': typeof AuthenticatedUploadModuleRoute
  '/modules/$moduleId': typeof AuthenticatedModulesModuleIdRouteWithChildren
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/modules/$moduleId/$topicId': typeof AuthenticatedModulesModuleIdTopicIdRouteWithChildren
  '/modules/$moduleId/$topicId/$chapterIdx': typeof AuthenticatedModulesModuleIdTopicIdChapterIdxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interns': typeof AuthenticatedInternsRoute
  '/managers': typeof AuthenticatedManagersRoute
  '/modules': typeof AuthenticatedModulesRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboard': typeof AuthenticatedOnboardRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/upload-module': typeof AuthenticatedUploadModuleRoute
  '/modules/$moduleId': typeof AuthenticatedModulesModuleIdRouteWithChildren
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/modules/$moduleId/$topicId': typeof AuthenticatedModulesModuleIdTopicIdRouteWithChildren
  '/modules/$moduleId/$topicId/$chapterIdx': typeof AuthenticatedModulesModuleIdTopicIdChapterIdxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/interns': typeof AuthenticatedInternsRoute
  '/_authenticated/managers': typeof AuthenticatedManagersRoute
  '/_authenticated/modules': typeof AuthenticatedModulesRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboard': typeof AuthenticatedOnboardRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/upload-module': typeof AuthenticatedUploadModuleRoute
  '/_authenticated/modules/$moduleId': typeof AuthenticatedModulesModuleIdRouteWithChildren
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/_authenticated/modules/$moduleId/$topicId': typeof AuthenticatedModulesModuleIdTopicIdRouteWithChildren
  '/_authenticated/modules/$moduleId/$topicId/$chapterIdx': typeof AuthenticatedModulesModuleIdTopicIdChapterIdxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/approvals'
    | '/dashboard'
    | '/interns'
    | '/managers'
    | '/modules'
    | '/notifications'
    | '/onboard'
    | '/performance'
    | '/profile'
    | '/reviews'
    | '/settings'
    | '/upload-module'
    | '/modules/$moduleId'
    | '/users/$userId'
    | '/modules/$moduleId/$topicId'
    | '/modules/$moduleId/$topicId/$chapterIdx'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/approvals'
    | '/dashboard'
    | '/interns'
    | '/managers'
    | '/modules'
    | '/notifications'
    | '/onboard'
    | '/performance'
    | '/profile'
    | '/reviews'
    | '/settings'
    | '/upload-module'
    | '/modules/$moduleId'
    | '/users/$userId'
    | '/modules/$moduleId/$topicId'
    | '/modules/$moduleId/$topicId/$chapterIdx'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/approvals'
    | '/_authenticated/dashboard'
    | '/_authenticated/interns'
    | '/_authenticated/managers'
    | '/_authenticated/modules'
    | '/_authenticated/notifications'
    | '/_authenticated/onboard'
    | '/_authenticated/performance'
    | '/_authenticated/profile'
    | '/_authenticated/reviews'
    | '/_authenticated/settings'
    | '/_authenticated/upload-module'
    | '/_authenticated/modules/$moduleId'
    | '/_authenticated/users/$userId'
    | '/_authenticated/modules/$moduleId/$topicId'
    | '/_authenticated/modules/$moduleId/$topicId/$chapterIdx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upload-module': {
      id: '/_authenticated/upload-module'
      path: '/upload-module'
      fullPath: '/upload-module'
      preLoaderRoute: typeof AuthenticatedUploadModuleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboard': {
      id: '/_authenticated/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof AuthenticatedOnboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/modules': {
      id: '/_authenticated/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof AuthenticatedModulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/managers': {
      id: '/_authenticated/managers'
      path: '/managers'
      fullPath: '/managers'
      preLoaderRoute: typeof AuthenticatedManagersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interns': {
      id: '/_authenticated/interns'
      path: '/interns'
      fullPath: '/interns'
      preLoaderRoute: typeof AuthenticatedInternsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/modules/$moduleId': {
      id: '/_authenticated/modules/$moduleId'
      path: '/$moduleId'
      fullPath: '/modules/$moduleId'
      preLoaderRoute: typeof AuthenticatedModulesModuleIdRouteImport
      parentRoute: typeof AuthenticatedModulesRoute
    }
    '/_authenticated/modules/$moduleId/$topicId': {
      id: '/_authenticated/modules/$moduleId/$topicId'
      path: '/$topicId'
      fullPath: '/modules/$moduleId/$topicId'
      preLoaderRoute: typeof AuthenticatedModulesModuleIdTopicIdRouteImport
      parentRoute: typeof AuthenticatedModulesModuleIdRoute
    }
    '/_authenticated/modules/$moduleId/$topicId/$chapterIdx': {
      id: '/_authenticated/modules/$moduleId/$topicId/$chapterIdx'
      path: '/$chapterIdx'
      fullPath: '/modules/$moduleId/$topicId/$chapterIdx'
      preLoaderRoute: typeof AuthenticatedModulesModuleIdTopicIdChapterIdxRouteImport
      parentRoute: typeof AuthenticatedModulesModuleIdTopicIdRoute
    }
  }
}

interface AuthenticatedModulesModuleIdTopicIdRouteChildren {
  AuthenticatedModulesModuleIdTopicIdChapterIdxRoute: typeof AuthenticatedModulesModuleIdTopicIdChapterIdxRoute
}

const AuthenticatedModulesModuleIdTopicIdRouteChildren: AuthenticatedModulesModuleIdTopicIdRouteChildren =
  {
    AuthenticatedModulesModuleIdTopicIdChapterIdxRoute:
      AuthenticatedModulesModuleIdTopicIdChapterIdxRoute,
  }

const AuthenticatedModulesModuleIdTopicIdRouteWithChildren =
  AuthenticatedModulesModuleIdTopicIdRoute._addFileChildren(
    AuthenticatedModulesModuleIdTopicIdRouteChildren,
  )

interface AuthenticatedModulesModuleIdRouteChildren {
  AuthenticatedModulesModuleIdTopicIdRoute: typeof AuthenticatedModulesModuleIdTopicIdRouteWithChildren
}

const AuthenticatedModulesModuleIdRouteChildren: AuthenticatedModulesModuleIdRouteChildren =
  {
    AuthenticatedModulesModuleIdTopicIdRoute:
      AuthenticatedModulesModuleIdTopicIdRouteWithChildren,
  }

const AuthenticatedModulesModuleIdRouteWithChildren =
  AuthenticatedModulesModuleIdRoute._addFileChildren(
    AuthenticatedModulesModuleIdRouteChildren,
  )

interface AuthenticatedModulesRouteChildren {
  AuthenticatedModulesModuleIdRoute: typeof AuthenticatedModulesModuleIdRouteWithChildren
}

const AuthenticatedModulesRouteChildren: AuthenticatedModulesRouteChildren = {
  AuthenticatedModulesModuleIdRoute:
    AuthenticatedModulesModuleIdRouteWithChildren,
}

const AuthenticatedModulesRouteWithChildren =
  AuthenticatedModulesRoute._addFileChildren(AuthenticatedModulesRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInternsRoute: typeof AuthenticatedInternsRoute
  AuthenticatedManagersRoute: typeof AuthenticatedManagersRoute
  AuthenticatedModulesRoute: typeof AuthenticatedModulesRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardRoute: typeof AuthenticatedOnboardRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUploadModuleRoute: typeof AuthenticatedUploadModuleRoute
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInternsRoute: AuthenticatedInternsRoute,
  AuthenticatedManagersRoute: AuthenticatedManagersRoute,
  AuthenticatedModulesRoute: AuthenticatedModulesRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardRoute: AuthenticatedOnboardRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUploadModuleRoute: AuthenticatedUploadModuleRoute,
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
